USE [master]
GO
/****** Object:  Database [TP06]    Script Date: 18/8/2025 08:58:06 ******/
CREATE DATABASE [TP06]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TP06', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TP06.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TP06_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TP06_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TP06] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TP06].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TP06] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TP06] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TP06] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TP06] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TP06] SET ARITHABORT OFF 
GO
ALTER DATABASE [TP06] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TP06] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TP06] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TP06] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TP06] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TP06] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TP06] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TP06] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TP06] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TP06] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TP06] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TP06] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TP06] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TP06] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TP06] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TP06] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TP06] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TP06] SET RECOVERY FULL 
GO
ALTER DATABASE [TP06] SET  MULTI_USER 
GO
ALTER DATABASE [TP06] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TP06] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TP06] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TP06] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TP06] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TP06] SET QUERY_STORE = OFF
GO
USE [TP06]
GO
/****** Object:  Table [dbo].[Lista]    Script Date: 18/8/2025 21:46:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Lista](
	[id_lista] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Lista] PRIMARY KEY CLUSTERED 
(
	[id_lista] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tarea]    Script Date: 18/8/2025 21:46:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tarea](
	[id_tarea] [int] IDENTITY(1,1) NOT NULL,
	[id_usuarioog] [int] NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[fechaCreacion] [date] NOT NULL,
	[estaFinalizada] [bit] NOT NULL,
	[estaBorrada] [bit] NOT NULL,
	[contenido] [varchar](500) NOT NULL,
	[id_lista] [int] NULL,
 CONSTRAINT [PK_Tarea] PRIMARY KEY CLUSTERED 
(
	[id_tarea] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tareaxUsuario]    Script Date: 18/8/2025 21:46:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tareaxUsuario](
	[id_Tarea] [int] NOT NULL,
	[id_Usuario] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 18/8/2025 21:46:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[id_usuario] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[password] [varchar](500) NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[agregarTarea]    Script Date: 18/8/2025 21:46:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[agregarTarea]
@pnombre varchar(50),
@pid_usuario int,
@pcontenido varchar(500)
AS
BEGIN 
		INSERT INTO Tarea (nombre, id_usuarioog, fechaCreacion, estaFinalizada, estaBorrada, contenido) VALUES (@pnombre,@pid_usuario, GETDATE(), 0, 0, @pcontenido)
		
		SELECT @@IDENTITY
END
GO
/****** Object:  StoredProcedure [dbo].[agregarTareayUser]    Script Date: 18/8/2025 21:46:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[agregarTareayUser]
@pidTarea int,
@pid_usuario int
AS
BEGIN 
		IF NOT EXISTS (SELECT 1 FROM tareaxUsuario WHERE id_tarea = @pidTarea AND id_usuario = @pid_usuario)
		BEGIN
		INSERT INTO tareaxUsuario(id_tarea,id_Usuario) VALUES (@pidTarea,@pid_usuario)
		END

END
GO
/****** Object:  StoredProcedure [dbo].[agregarUsuario]    Script Date: 18/8/2025 21:46:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[agregarUsuario]
@pnombreUsuario varchar(50),
@ppassword varchar(300)
AS
BEGIN 
	IF NOT EXISTS(SELECT 1 FROM Usuario WHERE username=@pnombreUsuario)
	BEGIN 
	INSERT INTO Usuario(username,password)VALUES(@pnombreUsuario,@ppassword)
	SELECT 1
	END
	ELSE
	BEGIN
		SELECT -1
	END
	
END
GO
USE [master]
GO
ALTER DATABASE [TP06] SET  READ_WRITE 
GO
